--------------------------------------------------------
-- Archivo creado  - viernes-junio-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ESCUELA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KEL"."ESCUELA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ESCUELA
--------------------------------------------------------

  CREATE TABLE "KEL"."ESCUELA" 
   (	"IDESCUELA" NUMBER(*,0), 
	"IDFACULTAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CANTALUMNOS" NUMBER(*,0), 
	"RECURSO_FISCAL" NUMBER(*,0), 
	"LICENCIADA" CHAR(1 BYTE), 
	"CLASIFICACION" NUMBER(*,0), 
	"FECHAREGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTAD
--------------------------------------------------------

  CREATE TABLE "KEL"."FACULTAD" 
   (	"IDFACULTAD" NUMBER(*,0), 
	"DESCFACULTAD" VARCHAR2(20 BYTE), 
	"FECHAREGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KEL.ESCUELA
SET DEFINE OFF;
Insert into KEL.ESCUELA (IDESCUELA,IDFACULTAD,NOMBRE,CANTALUMNOS,RECURSO_FISCAL,LICENCIADA,CLASIFICACION,FECHAREGISTRO) values ('1','1','INGENIERIA','100','2000','1','20',to_date('18/06/22','DD/MM/RR'));
Insert into KEL.ESCUELA (IDESCUELA,IDFACULTAD,NOMBRE,CANTALUMNOS,RECURSO_FISCAL,LICENCIADA,CLASIFICACION,FECHAREGISTRO) values ('2','3','INFORMATICAS','200','5000','1','15',to_date('19/06/22','DD/MM/RR'));
REM INSERTING into KEL.FACULTAD
SET DEFINE OFF;
Insert into KEL.FACULTAD (IDFACULTAD,DESCFACULTAD,FECHAREGISTRO) values ('1','INGENIERUIA MECANICA',to_date('17/06/22','DD/MM/RR'));
Insert into KEL.FACULTAD (IDFACULTAD,DESCFACULTAD,FECHAREGISTRO) values ('2','DERECHO',to_date('25/06/22','DD/MM/RR'));
Insert into KEL.FACULTAD (IDFACULTAD,DESCFACULTAD,FECHAREGISTRO) values ('3','INFORMATICA',to_date('26/06/22','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index ESCUELA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEL"."ESCUELA_PK" ON "KEL"."ESCUELA" ("IDESCUELA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KEL"."FACULTAD_PK" ON "KEL"."FACULTAD" ("IDFACULTAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ESCUELA
--------------------------------------------------------

  ALTER TABLE "KEL"."ESCUELA" MODIFY ("IDESCUELA" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("IDFACULTAD" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("CANTALUMNOS" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("RECURSO_FISCAL" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("LICENCIADA" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("CLASIFICACION" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" MODIFY ("FECHAREGISTRO" NOT NULL ENABLE);
  ALTER TABLE "KEL"."ESCUELA" ADD CONSTRAINT "ESCUELA_PK" PRIMARY KEY ("IDESCUELA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTAD
--------------------------------------------------------

  ALTER TABLE "KEL"."FACULTAD" MODIFY ("IDFACULTAD" NOT NULL ENABLE);
  ALTER TABLE "KEL"."FACULTAD" MODIFY ("DESCFACULTAD" NOT NULL ENABLE);
  ALTER TABLE "KEL"."FACULTAD" MODIFY ("FECHAREGISTRO" NOT NULL ENABLE);
  ALTER TABLE "KEL"."FACULTAD" ADD CONSTRAINT "FACULTAD_PK" PRIMARY KEY ("IDFACULTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESCUELA
--------------------------------------------------------

  ALTER TABLE "KEL"."ESCUELA" ADD CONSTRAINT "ESCUELA_FK1" FOREIGN KEY ("IDFACULTAD")
	  REFERENCES "KEL"."FACULTAD" ("IDFACULTAD") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESCUELA_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "KEL"."ESCUELA_TRG" 
BEFORE INSERT ON ESCUELA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDESCUELA IS NULL THEN
      SELECT ESCUELA_SEQ.NEXTVAL INTO :NEW.IDESCUELA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KEL"."ESCUELA_TRG" ENABLE;
